//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial.Logica.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMembresia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMembresia()
        {
            this.tbProveedor = new HashSet<tbProveedor>();
        }
    
        public int membCodigo { get; set; }
        public string membDescripcion { get; set; }
        public Nullable<int> membCantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProveedor> tbProveedor { get; set; }
    }
}
