//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial.Logica.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProducto
    {
        public int prodCodigo { get; set; }
        public string prodDescripcion { get; set; }
        public Nullable<int> prodCantidad { get; set; }
        public Nullable<int> prodValor { get; set; }
        public Nullable<int> provIdentificacion { get; set; }
        public Nullable<int> cateCodigo { get; set; }
    
        public virtual tbCategoria tbCategoria { get; set; }
        public virtual tbProveedor tbProveedor { get; set; }
    }
}
